name: Fetch NVDA Events

on:
  schedule:
    - cron: "7 13 * * *"   # run daily ~9am ET
  workflow_dispatch: {}    # allow manual trigger

jobs:
  fetch:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Fetch events
        run: |
          python scripts/fetch_events.py --ticker NVDA --start $(date -u +%F) --end 2025-12-31
      
      - name: Commit changes
        run: |
          git config user.name "event-bot"
          git config user.email "bot@users.noreply.github.com"
          git add -A
          git diff --staged --quiet || git commit -m "auto: update NVDA events $(date -u +%Y-%m-%d)"
          git push
